"""
This type stub file was generated by pyright.
"""

import contextlib
import functools
import json
import os
import subprocess
import tempfile
from __future__ import annotations
from typing import Any, Generator
from pdm.compat import resources_path

"""
A collection of functions that need to be called via a subprocess call.
"""
@functools.lru_cache
def get_python_abis(executable: str) -> list[str]:
    ...

def get_sys_config_paths(executable: str, vars: dict[str, str] | None = ..., kind: str = ...) -> dict[str, str]:
    """Return the sys_config.get_paths() result for the python interpreter"""
    ...

def get_pep508_environment(executable: str) -> dict[str, str]:
    """Get PEP 508 environment markers dict."""
    ...

def parse_setup_py(executable: str, path: str) -> dict[str, Any]:
    """Parse setup.py and return the kwargs"""
    ...

@functools.lru_cache
def get_uname(executable: str) -> os.uname_result:
    """Get uname of the system"""
    ...

@functools.lru_cache
def sysconfig_get_platform(executable: str) -> str:
    """Get platform from sysconfig"""
    ...
