"""
This type stub file was generated by pyright.
"""

from typing import Collection, Iterable
from pdm.cli.filters import GroupSelection
from pdm.cli.hooks import HookManager
from pdm.models.candidates import Candidate
from pdm.models.requirements import Requirement
from pdm.project import Project

def do_lock(project: Project, strategy: str = ..., tracked_names: Iterable[str] | None = ..., requirements: list[Requirement] | None = ..., dry_run: bool = ..., refresh: bool = ..., groups: list[str] | None = ..., strategy_change: list[str] | None = ..., hooks: HookManager | None = ...) -> dict[str, Candidate]:
    """Performs the locking process and update lockfile."""
    ...

def resolve_candidates_from_lockfile(project: Project, requirements: Iterable[Requirement], cross_platform: bool = ..., groups: Collection[str] | None = ...) -> dict[str, Candidate]:
    ...

def check_lockfile(project: Project, raise_not_exist: bool = ...) -> str | None:
    """Check if the lock file exists and is up to date. Return the lock strategy."""
    ...

def do_sync(project: Project, *, selection: GroupSelection, dry_run: bool = ..., clean: bool = ..., requirements: list[Requirement] | None = ..., tracked_names: Collection[str] | None = ..., no_editable: bool | Collection[str] = ..., no_self: bool = ..., reinstall: bool = ..., only_keep: bool = ..., fail_fast: bool = ..., hooks: HookManager | None = ...) -> None:
    """Synchronize project"""
    ...

def ask_for_import(project: Project) -> None:
    """Show possible importable files and ask user to decide"""
    ...

def print_pep582_command(project: Project, shell: str = ...) -> None:
    """Print the export PYTHONPATH line to be evaluated by the shell."""
    ...

def get_latest_pdm_version_from_pypi(project: Project, prereleases: bool = ...) -> str | None:
    """Get the latest version of PDM from PyPI."""
    ...

def get_latest_version(project: Project) -> str | None:
    """Get the latest version of PDM from PyPI, cache for 7 days"""
    ...

def check_update(project: Project) -> None:
    """Check if there is a new version of PDM available"""
    ...
