"""
This type stub file was generated by pyright.
"""

import argparse
from typing import Iterator, Sequence, TYPE_CHECKING
from pdm.project import Project

if TYPE_CHECKING:
    ...
class GroupSelection:
    def __init__(self, project: Project, *, default: bool = ..., dev: bool | None = ..., groups: Sequence[str] = ..., group: str | None = ..., excluded_groups: Sequence[str] = ...) -> None:
        ...

    @classmethod
    def from_options(cls, project: Project, options: argparse.Namespace) -> GroupSelection:
        ...

    def one(self) -> str:
        ...

    @property
    def is_unset(self) -> bool:
        ...

    def all(self) -> list[str] | None:
        ...

    def validate(self) -> None:
        ...

    def __iter__(self) -> Iterator[str]:
        ...

    def __contains__(self, group: str) -> bool:
        ...
