"""
This type stub file was generated by pyright.
"""

import contextlib
from typing import Any, Generator
from pdm.project.core import Project

class HookManager:
    def __init__(self, project: Project, skip: list[str] | None = ...) -> None:
        ...

    @contextlib.contextmanager
    def skipping(self, *names: str) -> Generator[None, None, None]:
        """
        Temporarily skip some hooks.
        """
        ...

    @property
    def skip_all(self) -> bool:
        ...

    @property
    def skip_pre(self) -> bool:
        ...

    @property
    def skip_post(self) -> bool:
        ...

    def should_run(self, name: str) -> bool:
        """
        Tells whether a task given its name should run or not
        according to the current skipping rules.
        """
        ...

    def try_emit(self, name: str, **kwargs: Any) -> None:
        """
        Emit a hook signal if rules allow it.
        """
        ...
