"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from pdm.models.candidates import Candidate

if TYPE_CHECKING:
    ...
class PdmException(Exception):
    ...


class PdmArgumentError(PdmException):
    ...


class PdmUsageError(PdmException):
    ...


class RequirementError(PdmUsageError, ValueError):
    ...


class PublishError(PdmUsageError):
    ...


class InvalidPyVersion(PdmUsageError, ValueError):
    ...


class CandidateNotFound(PdmException):
    ...


class CandidateInfoNotFound(PdmException):
    def __init__(self, candidate: Candidate) -> None:
        ...



class PDMWarning(Warning):
    ...


class PackageWarning(PDMWarning):
    ...


class PDMDeprecationWarning(PDMWarning, DeprecationWarning):
    ...


class ExtrasWarning(PDMWarning):
    def __init__(self, project_name: str, extras: list[str]) -> None:
        ...



class ProjectError(PdmUsageError):
    ...


class InstallationError(PdmException):
    ...


class UninstallError(PdmException):
    ...


class NoConfigError(PdmUsageError, KeyError):
    def __str__(self) -> str:
        ...



class NoPythonVersion(PdmUsageError):
    ...


class BuildError(PdmException, RuntimeError):
    ...
