"""
This type stub file was generated by pyright.
"""

import argparse
from pdm.cli.commands.base import BaseCommand
from pdm.project import Project

class Command(BaseCommand):
    """Import project metadata from other formats"""
    name = ...
    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        ...

    def handle(self, project: Project, options: argparse.Namespace) -> None:
        ...

    @staticmethod
    def do_import(project: Project, filename: str, format: str | None = ..., options: argparse.Namespace | None = ..., reset_backend: bool = ...) -> None:
        """Import project metadata from given file.

        :param project: the project instance
        :param filename: the file name
        :param format: the file format, or guess if not given.
        :param options: other options parsed to the CLI.
        """
        ...
