"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from pdm.cli.commands.base import BaseCommand
from pdm.models.python import PythonInfo
from argparse import ArgumentParser, Namespace, _SubParsersAction
from pdm.project.core import Project

if TYPE_CHECKING:
    ...
class Command(BaseCommand):
    """Manage installed Python interpreters"""
    arguments = ...
    def add_arguments(self, parser: ArgumentParser) -> None:
        ...

    @classmethod
    def register_to(cls, subparsers: _SubParsersAction, name: str | None = ..., **kwargs: Any) -> None:
        ...

    def handle(self, project: Project, options: Namespace) -> None:
        ...



class ListCommand(BaseCommand):
    """List all Python interpreters installed with PDM"""
    arguments = ...
    def handle(self, project: Project, options: Namespace) -> None:
        ...



class RemoveCommand(BaseCommand):
    """Remove a Python interpreter installed with PDM"""
    arguments = ...
    def add_arguments(self, parser: ArgumentParser) -> None:
        ...

    def handle(self, project: Project, options: Namespace) -> None:
        ...



class InstallCommand(BaseCommand):
    """Install a Python interpreter with PDM"""
    arguments = ...
    def add_arguments(self, parser: ArgumentParser) -> None:
        ...

    def handle(self, project: Project, options: Namespace) -> None:
        ...

    @staticmethod
    def install_python(project: Project, request: str) -> PythonInfo:
        ...
