"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Mapping, TypeVar
from pdm import termui

_T = TypeVar("_T", bound=Callable)
def convert_from(field: str | None = ..., name: str | None = ...) -> Callable[[_T], _T]:
    ...

class Unset(Exception):
    ...


class MetaConvertError(Exception):
    """A special exception that preserves the partial metadata that are already resolved."""
    def __init__(self, errors: list[str], *, data: dict[str, Any], settings: dict[str, Any]) -> None:
        ...

    def __str__(self) -> str:
        ...



class _MetaConverterMeta(type):
    def __init__(cls, name: str, bases: tuple[type, ...], ns: dict[str, Any]) -> None:
        ...



class MetaConverter(metaclass=_MetaConverterMeta):
    """Convert a metadata dictionary to PDM's format"""
    _converters: dict[str, Callable]
    def __init__(self, source: dict, ui: termui.UI | None = ...) -> None:
        ...

    def convert(self) -> tuple[Mapping[str, Any], Mapping[str, Any]]:
        ...



def make_inline_table(data: Mapping) -> dict:
    """Create an inline table from the given data."""
    ...

def make_array(data: list, multiline: bool = ...) -> list:
    ...

def array_of_inline_tables(value: list[Mapping], multiline: bool = ...) -> list[str]:
    ...
