"""
This type stub file was generated by pyright.
"""

from typing import Any, Mapping, TYPE_CHECKING
from pdm.models.requirements import Requirement
from argparse import Namespace
from os import PathLike
from pdm.models.candidates import Candidate
from pdm.project import Project

if TYPE_CHECKING:
    ...
class RequirementParser:
    """Reference:
    https://pip.pypa.io/en/stable/reference/requirements-file-format/
    """
    def __init__(self) -> None:
        ...

    def parse(self, filename: str) -> None:
        ...



def check_fingerprint(project: Project, filename: PathLike) -> bool:
    ...

def convert_url_to_source(url: str, name: str | None, trusted_hosts: list[str], type: str = ...) -> dict[str, Any]:
    ...

def convert(project: Project, filename: PathLike, options: Namespace) -> tuple[Mapping[str, Any], Mapping[str, Any]]:
    ...

def export(project: Project, candidates: list[Candidate] | list[Requirement], options: Namespace) -> str:
    ...
