"""
This type stub file was generated by pyright.
"""

from typing import Any, ClassVar
from pdm.builders.base import EnvBuilder

class EditableBuilder(EnvBuilder):
    """Build egg-info in isolated env with managed Python."""
    FALLBACK_BACKEND: ClassVar[dict[str, Any]] = ...
    def prepare_metadata(self, out_dir: str) -> str:
        ...

    def build(self, out_dir: str, metadata_directory: str | None = ...) -> str:
        ...
