"""
This type stub file was generated by pyright.
"""

from pdm.builders.base import EnvBuilder

class SdistBuilder(EnvBuilder):
    """Build sdist in isolated env with managed Python."""
    def build(self, out_dir: str, metadata_directory: str | None = ...) -> str:
        ...
