"""
This type stub file was generated by pyright.
"""

from pdm.builders.base import EnvBuilder

class WheelBuilder(EnvBuilder):
    """Build wheel in isolated env with managed Python."""
    def prepare_metadata(self, out_dir: str) -> str:
        ...

    def build(self, out_dir: str, metadata_directory: str | None = ...) -> str:
        ...
