"""
This type stub file was generated by pyright.
"""

from unearth.auth import MultiDomainBasicAuth
from pdm._types import RepositoryConfig
from pdm.termui import UI

class PdmBasicAuth(MultiDomainBasicAuth):
    """A custom auth class that differs from Pip's implementation in the
    following ways:

        - It shows an error message when credentials are not provided or correct.
    """
    def __init__(self, ui: UI, sources: list[RepositoryConfig]) -> None:
        ...



class Keyring:
    def __init__(self) -> None:
        ...

    def get_auth_info(self, url: str, username: str | None) -> tuple[str, str] | None:
        """Return the password for the given url and username.
        The username can be None.
        """
        ...

    def save_auth_info(self, url: str, username: str, password: str) -> bool:
        """Set the password for the given url and username.
        Returns whether the operation is successful.
        """
        ...



keyring = ...
