"""
This type stub file was generated by pyright.
"""

import unearth
from typing import Any, TYPE_CHECKING
from packaging.version import Version
from pdm.models.session import PDMPyPIClient

if TYPE_CHECKING:
    ...
class ReverseVersion(Version):
    """A subclass of version that reverse the order of comparison."""
    def __lt__(self, other: Any) -> bool:
        ...

    def __le__(self, other: Any) -> bool:
        ...

    def __gt__(self, other: Any) -> bool:
        ...

    def __ge__(self, other: Any) -> bool:
        ...



class PDMPackageFinder(unearth.PackageFinder):
    def __init__(self, session: PDMPyPIClient | None = ..., *, minimal_version: bool = ..., **kwargs: Any) -> None:
        ...
