"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from pathlib import Path
from typing import Any, TYPE_CHECKING
from packaging.version import Version
from pdm.models.venv import VirtualEnv
from findpython import PythonVersion

if TYPE_CHECKING:
    ...
class PythonInfo:
    """
    A convenient helper class that holds all information of a Python interpreter.
    """
    def __init__(self, py_version: PythonVersion) -> None:
        ...

    @classmethod
    def from_path(cls, path: str | Path) -> PythonInfo:
        ...

    @cached_property
    def valid(self) -> bool:
        ...

    def __hash__(self) -> int:
        ...

    def __eq__(self, o: Any) -> bool:
        ...

    @property
    def path(self) -> Path:
        ...

    @property
    def executable(self) -> Path:
        ...

    @cached_property
    def version(self) -> Version:
        ...

    @cached_property
    def implementation(self) -> str:
        ...

    @property
    def major(self) -> int:
        ...

    @property
    def minor(self) -> int:
        ...

    @property
    def micro(self) -> int:
        ...

    @property
    def version_tuple(self) -> tuple[int, ...]:
        ...

    @property
    def is_32bit(self) -> bool:
        ...

    def for_tag(self) -> str:
        ...

    @property
    def identifier(self) -> str:
        ...

    def get_venv(self) -> VirtualEnv | None:
        ...
