"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from html.parser import HTMLParser
from pdm._types import Package

@dataclass
class Result:
    name: str = ...
    version: str = ...
    description: str = ...
    def as_package(self) -> Package:
        ...



class SearchResultParser(HTMLParser):
    """A simple HTML parser for pypi.org search results."""
    def __init__(self) -> None:
        ...

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        ...

    def handle_data(self, data: str) -> None:
        ...

    def handle_endtag(self, tag: str) -> None:
        ...
