"""
This type stub file was generated by pyright.
"""

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, no_type_check
from pdm.compat import Distribution

@dataclass
class Setup:
    """
    Abstraction of a Python project setup file.
    """
    name: str | None = ...
    version: str | None = ...
    install_requires: list[str] = ...
    extras_require: dict[str, list[str]] = ...
    python_requires: str | None = ...
    summary: str | None = ...
    def update(self, other: Setup) -> None:
        ...

    def as_dict(self) -> dict[str, Any]:
        ...

    @classmethod
    def from_directory(cls, dir: Path) -> Setup:
        ...

    def as_dist(self) -> Distribution:
        ...



class _SetupReader:
    """
    Class that reads a setup.py file without executing it.
    """
    @classmethod
    def read_from_directory(cls, directory: Path) -> Setup:
        ...

    @staticmethod
    def read_pyproject_toml(file: Path) -> Setup:
        ...

    @no_type_check
    @classmethod
    def read_setup_py(cls, file: Path) -> Setup:
        ...

    @staticmethod
    def read_setup_cfg(file: Path) -> Setup:
        ...



class SetupDistribution(Distribution):
    def __init__(self, data: Setup) -> None:
        ...

    def read_text(self, filename: str) -> str | None:
        ...

    def locate_file(self, path: str | os.PathLike[str]) -> os.PathLike[str]:
        ...

    @property
    def metadata(self) -> dict[str, Any]:
        ...

    @property
    def requires(self) -> list[str] | None:
        ...
