"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from typing import Any
from dep_logic.specifiers import VersionSpecifier
from packaging.specifiers import SpecifierSet

@lru_cache
def get_specifier(version_str: str) -> SpecifierSet:
    ...

_legacy_specifier_re = ...
@lru_cache
def fix_legacy_specifier(specifier: str) -> str:
    """Since packaging 22.0, legacy specifiers like '>=4.*' are no longer
    supported. We try to normalize them to the new format.
    """
    ...

class PySpecSet(SpecifierSet):
    """A custom SpecifierSet that supports merging with logic operators (&, |)."""
    PY_MAX_MINOR_VERSION = ...
    MAX_MAJOR_VERSION = ...
    __slots__ = ...
    def __init__(self, spec: str | VersionSpecifier = ...) -> None:
        ...

    def __hash__(self) -> int:
        ...

    def __str__(self) -> str:
        ...

    def __eq__(self, other: Any) -> bool:
        ...

    def is_empty(self) -> bool:
        """Check whether the specifierset contains any valid versions."""
        ...

    def is_any(self) -> bool:
        """Return True if the specifierset accepts all versions."""
        ...

    def __repr__(self) -> str:
        ...

    def __and__(self, other: Any) -> PySpecSet:
        ...

    def __or__(self, other: Any) -> PySpecSet:
        ...

    @lru_cache
    def is_superset(self, other: str | PySpecSet) -> bool:
        ...

    @lru_cache
    def is_subset(self, other: str | PySpecSet) -> bool:
        ...

    def as_marker_string(self) -> str:
        ...
