"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Iterator, Mapping
from pdm.compat import importlib_metadata as im

default_context = ...
class EgglinkFinder(im.DistributionFinder):
    @classmethod
    def find_distributions(cls, context: im.DistributionFinder.Context = ...) -> Iterable[im.Distribution]:
        ...



def distributions(path: list[str]) -> Iterable[im.Distribution]:
    """Find distributions in the paths. Similar to `importlib.metadata`'s
    implementation but with the ability to discover egg-links.
    """
    ...

class WorkingSet(Mapping[str, im.Distribution]):
    """A dictionary of currently installed distributions"""
    def __init__(self, paths: list[str] | None = ..., shared_paths: list[str] | None = ...) -> None:
        ...

    def __getitem__(self, key: str) -> im.Distribution:
        ...

    def is_owned(self, key: str) -> bool:
        ...

    def __len__(self) -> int:
        ...

    def __iter__(self) -> Iterator[str]:
        ...

    def __repr__(self) -> str:
        ...
