"""
This type stub file was generated by pyright.
"""

from functools import wraps
from . import cookiecutter, cruft, diff, generate, iohelper
from examples import example

__all__ = ["cookiecutter", "cruft", "diff", "example", "generate", "iohelper"]
