"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, Optional
from git import Repo

CookiecutterContext = Dict[str, Any]
def resolve_template_url(url: str) -> str:
    ...

def get_cookiecutter_repo(template_git_url: str, cookiecutter_template_dir: Path, checkout: Optional[str] = ..., **clone_kwargs) -> Repo:
    ...

def generate_cookiecutter_context(template_git_url: str, cookiecutter_template_dir: Path, config_file: Optional[Path] = ..., default_config: bool = ..., extra_context: Optional[Dict[str, Any]] = ..., no_input: bool = ...) -> CookiecutterContext:
    ...
