"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict
from git import Repo

CruftState = Dict[str, Any]
def get_cruft_file(project_dir_path: Path, exists: bool = ...) -> Path:
    ...

def is_project_updated(repo: Repo, current_commit: str, latest_commit: str, strict: bool) -> bool:
    ...

def json_dumps(cruft_state: Dict[str, Any]) -> str:
    ...
