"""
This type stub file was generated by pyright.
"""

from pathlib import Path

DIFF_SRC_PREFIX = ...
DIFF_DST_PREFIX = ...
def get_diff(repo0: Path, repo1: Path) -> str:
    """Compute the raw diff between two repositories."""
    ...

def display_diff(repo0: Path, repo1: Path): # -> None:
    """Displays the diff between two repositories."""
    ...
