"""
This type stub file was generated by pyright.
"""

import argparse
from __future__ import annotations
from pdm.cli.commands.base import BaseCommand
from pdm.cli.commands.fix.fixers import BaseFixer, PackageTypeFixer, ProjectConfigFixer
from pdm.exceptions import PdmUsageError
from pdm.project import Project
from pdm.termui import Emoji

class Command(BaseCommand):
    """Fix the project problems according to the latest version of PDM"""
    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        ...

    @staticmethod
    def find_problems(project: Project) -> list[tuple[str, BaseFixer]]:
        """Get the problems in the project"""
        ...

    @staticmethod
    def check_problems(project: Project, strict: bool = ...) -> None:
        """Check the problems in the project"""
        ...

    @staticmethod
    def get_fixers(project: Project) -> list[BaseFixer]:
        """Return a list of fixers to check, the order matters"""
        ...

    def handle(self, project: Project, options: argparse.Namespace) -> None:
        ...
