"""
This type stub file was generated by pyright.
"""

import abc
from pdm.project import Project
from pdm.termui import Verbosity

class BaseFixer(abc.ABC):
    """Base class for fixers"""
    identifier: str
    breaking: bool = ...
    def __init__(self, project: Project) -> None:
        ...

    def log(self, message: str, verbosity: Verbosity = ...) -> None:
        ...

    @abc.abstractmethod
    def get_message(self) -> str:
        """Return a description of the problem"""
        ...

    @abc.abstractmethod
    def fix(self) -> None:
        """Perform the fix"""
        ...

    @abc.abstractmethod
    def check(self) -> bool:
        """Check if the problem exists"""
        ...



class ProjectConfigFixer(BaseFixer):
    """Fix the project config"""
    identifier = ...
    def get_message(self) -> str:
        ...

    def fix(self) -> None:
        ...

    def check(self) -> bool:
        ...



class PackageTypeFixer(BaseFixer):
    identifier = ...
    def get_message(self) -> str:
        ...

    def check(self) -> bool:
        ...

    def fix(self) -> None:
        ...
