"""
This type stub file was generated by pyright.
"""

"""Global configuration handling."""
logger = ...
USER_CONFIG_PATH = ...
BUILTIN_ABBREVIATIONS = ...
DEFAULT_CONFIG = ...

def merge_configs(default, overwrite):
    """Recursively update a dict with the key/value pair of another.

    Dict values that are dictionaries themselves will be updated, whilst
    preserving existing keys.
    """
    ...

def get_config(config_path):
    """Retrieve the config from the specified path, returning a config dict."""
    ...

def get_user_config(
    config_file=..., default_config=...
):  # -> dict[str, str | OrderedDict[Any, Any] | dict[str, str]]:
    """Return the user config as a dict.

    If ``default_config`` is True, ignore ``config_file`` and return default
    values for the config parameters.

    If ``default_config`` is a dict, merge values with default values and return them
    for the config parameters.

    If a path to a ``config_file`` is given, that is different from the default
    location, load the user config from that.

    Otherwise look up the config file path in the ``COOKIECUTTER_CONFIG``
    environment variable. If set, load the config from this path. This will
    raise an error if the specified path is not valid.

    If the environment variable is not set, try the default config file path
    before falling back to the default config values.
    """
    ...
