"""
This type stub file was generated by pyright.
"""

from jinja2.ext import Extension

"""Jinja2 extensions."""

class JsonifyExtension(Extension):
    """Jinja2 extension to convert a Python object to JSON."""
    def __init__(self, environment) -> None:
        """Initialize the extension with the given environment."""
        ...

class RandomStringExtension(Extension):
    """Jinja2 extension to create a random string."""
    def __init__(self, environment) -> None:
        """Jinja2 Extension Constructor."""
        ...

class SlugifyExtension(Extension):
    """Jinja2 Extension to slugify string."""
    def __init__(self, environment) -> None:
        """Jinja2 Extension constructor."""
        ...

class UUIDExtension(Extension):
    """Jinja2 Extension to generate uuid4 string."""
    def __init__(self, environment) -> None:
        """Jinja2 Extension constructor."""
        ...

class TimeExtension(Extension):
    """Jinja2 Extension for dates and times."""

    tags = ...
    def __init__(self, environment) -> None:
        """Jinja2 Extension constructor."""
        ...

    def parse(self, parser):  # -> Output:
        """Parse datetime template and add datetime value."""
        ...
