"""
This type stub file was generated by pyright.
"""

"""Module for setting up logging."""
LOG_LEVELS = ...
LOG_FORMATS = ...
def configure_logger(stream_level=..., debug_file=...): # -> Logger:
    """Configure logging for cookiecutter.

    Set up logging to stdout with given level. If ``debug_file`` is given set
    up logging to file with DEBUG level.
    """
    ...
