"""
This type stub file was generated by pyright.
"""

import os
from typing import Optional

"""Utility functions for handling and fetching repo archives in zip format."""
def unzip(zip_uri: str, is_url: bool, clone_to_dir: os.PathLike[str] = ..., no_input: bool = ..., password: Optional[str] = ...): # -> str:
    """Download and unpack a zipfile at a given URI.

    This will download the zipfile to the cookiecutter repository,
    and unpack into a temporary directory.

    :param zip_uri: The URI for the zipfile.
    :param is_url: Is the zip URI a URL or a file?
    :param clone_to_dir: The cookiecutter repository directory
        to put the archive into.
    :param no_input: Do not prompt for user input and eventually force a refresh of
        cached resources.
    :param password: The password to use when unpacking the repository.
    """
    ...
