"""
This type stub file was generated by pyright.
"""

from pdm.environments import BaseEnvironment
from pdm.models.requirements import Requirement

def install_requirements(reqs: list[Requirement], environment: BaseEnvironment, clean: bool = ..., use_install_cache: bool = ...) -> None:
    """Resolve and install the given requirements into the environment."""
    ...
