"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from pdm.compat import Distribution
from pdm.installers.uninstallers import BaseRemovePaths
from pdm.environments import BaseEnvironment
from pdm.models.candidates import Candidate

if TYPE_CHECKING:
    ...
class InstallManager:
    """The manager that performs the installation and uninstallation actions."""
    NO_CACHE_PACKAGES = ...
    def __init__(self, environment: BaseEnvironment, *, use_install_cache: bool = ..., rename_pth: bool = ...) -> None:
        ...

    def install(self, candidate: Candidate) -> Distribution:
        """Install a candidate into the environment, return the distribution"""
        ...

    def get_paths_to_remove(self, dist: Distribution) -> BaseRemovePaths:
        """Get the path collection to be removed from the disk"""
        ...

    def uninstall(self, dist: Distribution) -> None:
        """Perform the uninstallation for a given distribution"""
        ...

    def overwrite(self, dist: Distribution, candidate: Candidate) -> None:
        """An in-place update to overwrite the distribution with a new candidate"""
        ...
