"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from pathlib import Path
from pdm.environments.base import BaseEnvironment

class PythonLocalEnvironment(BaseEnvironment):
    """A project environment that installs packages into
    the local `__pypackages__` directory(PEP 582).
    """
    is_local = ...
    @property
    def process_env(self) -> dict[str, str]:
        ...

    @cached_property
    def packages_path(self) -> Path:
        """The local packages path."""
        ...

    def get_paths(self, dist_name: str | None = ...) -> dict[str, str]:
        ...

    def update_shebangs(self, new_path: str) -> None:
        """Update the shebang lines"""
        ...
