"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from pdm.environments.base import BaseEnvironment
from pdm.models.working_set import WorkingSet
from pdm.project import Project

if TYPE_CHECKING:
    ...
class PythonEnvironment(BaseEnvironment):
    """A project environment that is directly derived from a Python interpreter"""
    def __init__(self, project: Project, *, python: str | None = ..., prefix: str | None = ...) -> None:
        ...

    def get_paths(self, dist_name: str | None = ...) -> dict[str, str]:
        ...

    @property
    def process_env(self) -> dict[str, str]:
        ...

    def get_working_set(self) -> WorkingSet:
        ...
