"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Union
from click import ClickException

"""Contains all custom exceptions raised by cruft."""
class CruftError(ClickException):
    """The base exception for any error originating from the cruft project."""
    ...


class UnableToFindCookiecutterTemplate(CruftError):
    """Raised when Cruft is unable to find a cookiecutter template."""
    def __init__(self, directory: Union[str, Path]) -> None:
        ...



class NoCruftFound(CruftError):
    """Raised when no .cruft.json state is found in the current directory."""
    def __init__(self, directory: Union[str, Path]) -> None:
        ...



class CruftAlreadyPresent(CruftError):
    """Raised when there is an attempt to create a new .cruft.json file but one already exists."""
    def __init__(self, file_location: Union[str, Path]) -> None:
        ...



class InvalidCookiecutterRepository(CruftError):
    """Raised when an invalid cookiecutter repository is provided."""
    def __init__(self, cookiecutter_repo: str, details: str = ...) -> None:
        ...



class ChangesetUnicodeError(CruftError):
    """Raised when `cruft update` is unable to generate the change"""
    def __init__(self) -> None:
        ...
