"""
This type stub file was generated by pyright.
"""

from typing import Any, Mapping
from tomlkit import TOMLDocument, items
from pdm.project.toml_file import TOMLBase

class PyProject(TOMLBase):
    """The data object representing th pyproject.toml file"""
    def read(self) -> TOMLDocument:
        ...

    def write(self, show_message: bool = ...) -> None:
        """Write the TOMLDocument to the file."""
        ...

    @property
    def is_valid(self) -> bool:
        ...

    @property
    def metadata(self) -> items.Table:
        ...

    @property
    def settings(self) -> items.Table:
        ...

    @property
    def build_system(self) -> dict:
        ...

    @property
    def resolution(self) -> Mapping[str, Any]:
        """A compatible getter method for the resolution overrides
        in the pyproject.toml file.
        """
        ...

    @property
    def allow_prereleases(self) -> bool | None:
        ...

    def content_hash(self, algo: str = ...) -> str:
        """Generate a hash of the sensible content of the pyproject.toml file.
        When the hash changes, it means the project needs to be relocked.
        """
        ...

    @property
    def plugins(self) -> list[str]:
        ...
