"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Mapping
from tomlkit.toml_document import TOMLDocument
from tomlkit.toml_file import TOMLFile
from pdm import termui

class TOMLBase(TOMLFile):
    def __init__(self, path: str | Path, *, ui: termui.UI) -> None:
        ...

    def read(self) -> TOMLDocument:
        ...

    def set_data(self, data: Mapping[str, Any]) -> None:
        """Set the data of the TOML file."""
        ...

    def reload(self) -> None:
        ...

    def write(self) -> None:
        ...

    def exists(self) -> bool:
        ...

    def empty(self) -> bool:
        ...
