"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional
from .utils import example

@example()
def check(project_dir: Path = ..., checkout: Optional[str] = ..., strict: bool = ...) -> bool:
    """Checks to see if there have been any updates to the Cookiecutter template
    used to generate this project."""
    ...
