"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional

def diff(project_dir: Path = ..., exit_code: bool = ..., checkout: Optional[str] = ...) -> bool:
    """Show the diff between the project and the linked Cookiecutter template"""
    ...
