"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, Optional
from .utils import example

@example("https://github.com/timothycrosley/cookiecutter-python/")
def link(template_git_url: str, project_dir: Path = ..., checkout: Optional[str] = ..., no_input: bool = ..., config_file: Optional[Path] = ..., default_config: bool = ..., extra_context: Optional[Dict[str, Any]] = ..., directory: Optional[str] = ...) -> bool:
    """Links an existing project created from a template, to the template it was created from."""
    ...
