"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, Optional
from .utils import example

@example(skip_apply_ask=False)
@example()
def update(project_dir: Path = ..., cookiecutter_input: bool = ..., refresh_private_variables: bool = ..., skip_apply_ask: bool = ..., skip_update: bool = ..., checkout: Optional[str] = ..., strict: bool = ..., allow_untracked_files: bool = ..., extra_context: Optional[Dict[str, Any]] = ..., extra_context_file: Optional[Path] = ...) -> bool:
    """Update specified project's cruft to the latest and greatest release."""
    ...
